name: Code Style

on:
    push:
    pull_request:

permissions: write-all

jobs:
    Checks:
        uses: TheDragonCode/.github/.github/workflows/code-style.yml@main
        with:
            node: false
