name: Code Style

on:
    push:
    pull_request:

permissions: write-all

jobs:
    Styler:
        uses: TheDragonCode/.github/.github/workflows/code-style.yml@copilot/fix-f72fad4a-fa22-4792-9243-4789ccffdd01
        with:
            node: false
