name: Code Style

on:
    push:

permissions: {}

jobs:
    Checks:
        permissions:
            artifact-metadata: write
            contents: write
            pull-requests: write

        uses: TheDragonCode/.github/.github/workflows/code-style.yml@114cea00473063594c1ac778a22344341c177a70
        with:
            node: false
