name: Update license

on:
  schedule:
    - cron: '0 3 1 1 *'
  workflow_dispatch:

permissions: {}

jobs:
  Update:
    permissions:
      contents: write
      pull-requests: write

    uses: TheDragonCode/.github/.github/workflows/license.yml@114cea00473063594c1ac778a22344341c177a70
