name: Preview Updater

on:
    schedule:
        -   cron: '20 2 * * *'
    workflow_dispatch:

permissions: {}

jobs:
    preview:
        permissions:
            contents: write
            pull-requests: write

        uses: TheDragonCode/.github/.github/workflows/preview.yml@114cea00473063594c1ac778a22344341c177a70
