name: Release Drafter

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions: {}

jobs:
    Update:
        permissions:
            contents: write
            pull-requests: write

        uses: TheDragonCode/.github/.github/workflows/release-drafter.yml@114cea00473063594c1ac778a22344341c177a70
