name: Test Documentation

on:
    push:
        branches-ignore:
            - main

permissions:
    contents: read

env:
    COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}
    INSTANCE: docs/laravel-feeds
    ARTIFACT_DOCS: webHelpLARAVEL-FEEDS2-all.zip
    BUILDER_VERSION: 2025.04.8412

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
                with:
                    fetch-depth: 0

            -   name: Build documentation
                uses: JetBrains/writerside-github-action@738910d7cf197d67188300d0e0f84b2e708db3cf
                with:
                    instance: ${{ env.INSTANCE }}
                    artifact: ${{ env.ARTIFACT_DOCS }}
                    docker-version: ${{ env.BUILDER_VERSION }}


            -   name: Test documentation
                uses: JetBrains/writerside-checker-action@79ff89902dcd3d5c5a3f26a79bc35830377f38c5
                with:
                    instance: ${{ env.INSTANCE }}
